channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip=23.2.1
  - pre-commit=3.5.0
  - python=3.12.0
  - ruff=0.1.6
  - jupyter=1.0.0
  - biopython=1.83
  - r-irkernel=1.3.2
  - r-tidyverse=2.0.0
  - r-umap=0.2.10.0
  - r-rtsne=0.17
  - r-ggextra=0.10.0
  - r-ggrepel=0.9.5
  - r-ggforce=0.4.2
  - r-broom=1.0.6
  - r-janitor=2.2.0
  - seqkit=2.8.0
  - blast=2.15.0
  - seqtk=1.4
  - xlsx2csv=0.8.1
  - transdecoder=5.7.1 
